cacheserver_container:
	sudo docker build -t ansible-ms-cacheserver .

run_cacheserver_container_bash:
	sudo docker run -i -t ansible-ms-cacheserver /bin/bash

#run_cacheserver_container_apache:
#	sudo docker run -d -p 1800:80 ansible-ms-cacheserver /usr/sbin/apache2ctl -D FOREGROUND
